;; Generated by :claw at 2021-07-11T16:04:09.888356Z
(asdf:defsystem #:claw-glslang-bindings
  :description "Bindings generated by claw-glslang/wrapper"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))